on: [push, workflow_dispatch]

jobs:
  build:
    name: "🥔 Build Static Tatertot & Push changes"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: node ./src/index.js > index.html
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: '🥔 Update Tatertot Static Site'

